# Generated by Django 2.2 on 2020-04-12 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_user_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='phone',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(choices=[('iphone', 'iphone'), ('redmi', 'redmi'), ('samsung', 'samsung')], default='', max_length=200)),
                ('model', models.CharField(max_length=200)),
                ('price', models.CharField(max_length=200)),
                ('specification', models.TextField()),
                ('image', models.ImageField(upload_to='images/')),
            ],
        ),
    ]
