# Generated by Django 2.2 on 2020-04-17 18:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_auto_20200417_1734'),
    ]

    operations = [
        migrations.AddField(
            model_name='phone',
            name='sale',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='phone',
            name='sale_price',
            field=models.CharField(default='10', max_length=100),
        ),
        migrations.AlterField(
            model_name='review',
            name='phone',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.Phone'),
        ),
    ]
