# Generated by Django 2.2 on 2020-04-17 20:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_auto_20200418_0052'),
    ]

    operations = [
        migrations.AddField(
            model_name='phone',
            name='final_price',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='review',
            name='phone',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.Phone'),
        ),
    ]
