# Generated by Django 2.2 on 2020-04-20 13:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0013_auto_20200420_1915'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='phone',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.Phone'),
        ),
        migrations.AlterField(
            model_name='review',
            name='phone',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.Phone'),
        ),
    ]
